### ISSUE TITLE
URL til LiveRes API legges i config

### ISSUE THREAD

**Issue by palkitt** [Taune/EmiTagCheck#10]
URL for LiveRes API kan med fordel legges i config. Da kan man benytte lokal server når man ønsker. F.eks blir variabelen:
LiveResURL er default "https://api.freidig.idrett.no/" og kan settes ved lokal base "127.0.0.1/api/"

**Comment by Taune** [comment]
URL for LiveRes-server er lagt inn i config-fil og kan korrigeres der.
