### ISSUE TITLE
Offline startliste fra LiveRes

### ISSUE THREAD

**Issue by palkitt** [Taune/EmiTagCheck#11]
Foreslår å lage en funksjon som lagrer siste startliste fra LiveRes til lokal fil. Kan være i eTiming startlisteformat. Vurdere auto opplasting av denne typen fil om den ligger lagret på bestemt katalog (da trenger ikke brukeren tenke på å laste inn startliste ved en restart).

**Comment by Taune** [comment]
Brikkesjekkfil blir opprettet ved lesing av startliste fra LiveRes. Denne blir lagret lokalt på samme katalog som log-fil (vanligvis c:\temp\). Filnavn vil være "LiveResStartlist{dato}.csv".
