### ISSUE TITLE
Lagring av valgt arrangement ved avslutning

### ISSUE THREAD

**Issue by palkitt** [Taune/EmiTagCheck#12]
Foreslår at hvilket arrangement (LiveRes) som er valgt lagres (oppdatering av config fil?) slik at ved restart av programmet kommer dette valget opp. Det kan godt gjelde andre innstillinger som lydalternativ og temp-katalog også.

**Comment by Taune** [comment]
Lagring av info til config-fil er nå korrigert i versjon 26.01.2021.
