### ISSUE TITLE
Sende melding om at brikke er sjekket ved tildeling av ukjent

### ISSUE THREAD

**Issue by palkitt** [Taune/EmiTagCheck#14]
Ved tildeling av startnummer til ukjent brikke bør det sendes melding om at brikke er sjekket på den løperen som brikka er tildelt. Det virker ikke som det skjer i gjeldende versjon.

**Comment by Taune** [comment]
Ved bytte av brikke blir det nås sendt melding til LiveRes om at brikke er sjekket.
