### ISSUE TITLE
Programmet fryser ved dårlig nettforbindelse

### ISSUE THREAD

**Issue by implementore** [Taune/EmiTagCheck#17]
Ved dårlig nettforbindelse tok det opptil 15 sekunder før navnet kom opp, selv om startlista var synkronisert med LiveRes. Tydeligvis kaller programmet en api og venter på svar før det sjekker den lagra lista. Programmet fryser helt, selv klokka oppe til høyre stopper.

Vi løste det ved å koble nettet fra, da kom navnet med en gang, og koble til manuelt jevnlig for å synkronisere med LiveRes. Men det er bedre om programmet gir opp selv etter noen millisekunder.

Jeg har reprodusert problemet senere ved å bruke trådløst nett via mobilen, og legge den langt unna så den nester mister signalet.

**Comment by Taune** [comment]
Takk for tips. Jeg får samme feil med at programmet henger seg når nettet ikke er tilgjengelig. Jeg skal få lagt inn en funksjon som gjør at den stopper innlesing ved manglende nett. Jeg skal også få fikset en løsning som sender meldinger om brikkeendring mm på nytt om nettet er borte et øyeblikk. Jeg skal gi beskjed når dette er fikset :-)
Torgeir

**Comment by implementore** [comment]
Flott! Nå har jeg planer om å bruke programmet 6. mai et stykke utenfor allfarvei, tror du at du har ny versjon klar til da?

Hilsen Tore.

**Comment by Taune** [comment]
Hei Tore

Jeg har lagt ut en oppdatert versjon programmet hvor jeg har lagt inn en sjekk om at det er internettforbindelse før startliste blir lest og meldinger sendt:
https://github.com/Taune/EmiTagCheck/releases/download/2023-04-04/brikkesjekk.zip

Ta kontakt dersom det fortsatt er noen problemer eller om du har tips til forbedringer.

Torgeir

**Comment by implementore** [comment]
Takker, det ser bedre ut.
