### ISSUE TITLE
Registrert sjekket ved endring av brikkenummer

### ISSUE THREAD

**Issue by palkitt** [Taune/EmiTagCheck#8]
Når en ukjent brikke til tilordnet et startnummer bør det sendes en melding om at aktuell løpers brikke er sjekket (LiveRes API-metode setecardchecked). Dette i tillegg til API-metode for å endre brikkenummer.

**Comment by Taune** [comment]
Lagt inn API-kall for at brikke er sjekket (setecardchecked) ved bruk av brikkebytte-funksjon.
